# this script reads in the cropped data and makes QC plots
#
# input: cropped data files generated by crop_raw_data.R
# output: QC plots
#
#
# before running this script, update the file paths below
# - to toggle a line between commented (#...) and uncommented (...), use 
#   Shift-Control-C (Windows) or Shift-Command-C (Mac)
# - make sure to add a slash "/" at the end of each file path!
#

source("dataQCfunctions.R")

# directory containing cropped data to be plotted
cropped_loc <- "2022/2022 summer_NEW/2. Cropped files/2. Cropped csv/"
# directory where QC plots will be stored
qc_plots_loc <- paste0(base_loc, "3. QC Plots/")

# get a list of all the cropped files
filenames <- list.files(path = cropped_loc, pattern=".csv")
# this is now a list of all filenames; we haven't read in the data yet, but
# make sure this lists all the cropped files you want to plot
filenames

# make QC plots!
make_qc_plots_of_cropped_data(cropped_loc, qc_plots_loc)


