#' Make QC plots of cropped data
#'
#' This function is intended to be used on cropped data, such as the csv files created by crop_raw_data().
#'
#' @param cropped_loc File path to the directory containing the cropped data
#' generated by crop_raw_data() to use in making QC plots. These files must be
#' in csv format. The names of the cropped data files must start with
#' <sitename>_<medium>_<deployseason>_<deployyear>. For example, a file with
#' air data from site NolanLower and deployment date Summer 2023 should have
#' a filename starting with NolanLower_air_sum_23, like
#' NolanLower_air_sum_23_cropped.csv.
#'
#' @param qc_plots_loc File path to the directory where QC plots will be stored.
#'
#' @return
#' @export
#'
#' @examples
#'
#' # this code assumes you already have some cropped data available
#' # so for the example, let's crop some of the raw data that is
#' # provided with the dataQCtools package
#' example_loc = fs::path_package("extdata", package = "dataQCtools")
#' base_loc = paste0(example_loc, "/data/2022_summer/")
#' rawdata_loc = paste0(base_loc, "1_raw_csv/")
#' cropped_loc = base_loc
#' ldrtimes_fn = "LDRTimes_summer22.xlsx"
#' # first let's delete any files that are already there, so that if you
#' # have many files we start fresh and just process a few
#' unlink(paste0(cropped_loc, "2_cropped_csv/*"))
#' # now let's crop just three files for us to QC
#' crop_raw_data(rawdata_loc, ldrtimes_fn, cropped_loc, nfiles = 3)
#'
#' cropped_loc <- paste0(base_loc, "2_cropped_csv/")
#' qc_plots_loc <- base_loc #paste0(base_loc, "3_qc_plots/")
#'
#' # get a list of all the cropped data files
#' filenames <- list.files(path = cropped_loc, pattern=".csv")
#' # this is now a list of all filenames; we haven't read in the data yet, but
#' # make sure this lists all the cropped data files you want to plot:
#' filenames
#'
#' # then make QC plots
#' make_qc_plots_of_cropped_data(cropped_loc, qc_plots_loc)
#'
make_qc_plots_of_cropped_data = function(cropped_loc, qc_plots_loc){
  qc_plots_loc = paste0(qc_plots_loc, "3_qc_plots/")
  dir.create(qc_plots_loc, showWarnings = FALSE)

  # Make list of file names to plot
  filenames <- list.files(path = cropped_loc, pattern=".csv")

  # Loop to read all the data files and combine them into one datafile for easier plotting
  Combined <-NULL # Create new data frame to hold combined data

  cat("Reading in cropped data files...", fill = TRUE)
  i = 0
  for (selection in filenames) {
    i = i+1
    #selection = filenames[1] # for troubleshooting the for-loop
    cat(paste0("Reading file ", i, " of ", length(filenames), ": ", selection), fill = TRUE)
    # split the filename string everywhere there is an underscore or period
    # so that we can get the following metadata from it:
    #  site name, deployment season and year, and media (air/water)
    info_from_filename = unlist(strsplit(selection, split="[_.]"))[1:4]
    sitename = info_from_filename[1]
    media = info_from_filename[2] # air or water; assumes this info is the third chunk after splitting the filename
    deploy_season = info_from_filename[3]
    if(deploy_season != "sum" & deploy_season != "fall"){
      stop("filename does not say sum or fall.")
    }
    deploy_year = 2000 + as.integer(info_from_filename[4]) # or we can format as character

    oneread <- read.csv(
      file = paste0(cropped_loc, selection), as.is=T, skip=1, fill=T, header=F
    ) %>% ## Reads the selected datafile.
      dplyr::select(1:3) %>% #select the first 3 columns (remove air temp from Hoh River sites)
      # add the metadata as variables/columns
      dplyr::mutate(sitename = sitename,
             media = media,
             deploy_season = deploy_season,
             deploy_year = deploy_year)
    Combined <- dplyr::bind_rows(Combined, oneread)  ## Adds the datafile's data to the existing combined datafile.

  } # filenames loop
  cat("Done reading in cropped data.", fill = TRUE)

  cat("Computing temperature differences...", fill = TRUE)
  # only compute AWMaxDiff and AirRange if there is air data for at least one site
  if("air" %in% unique(Combined$media)){
    Combined <- Combined %>%
      dplyr::rename(row = .data$V1, datetime = .data$V2, temp = .data$V3) %>%  # Rename the first three variables that came from the csv file
      dplyr::mutate(datetime = lubridate::ymd_hms(.data$datetime)) %>%  # change format of datetime column
      dplyr::mutate(date = lubridate::date(.data$datetime)) %>%
      dplyr::group_by(.data$sitename, .data$date, .data$media)  %>%  # compute daily max/min by site, date, and media (air/water)
      dplyr::summarize(dailymax = max(.data$temp, na.rm = TRUE),
                       dailymin = min(.data$temp, na.rm = TRUE)) %>%
      # pivot dataframe to add air or water to column name; this is necessary to calculate stats
      # this puts air and water on the same rows so we can just subtract columns in the next line
      # this requires that at least one site has air temperature!
      tidyr::pivot_wider(names_from = .data$media,
                         values_from = c(.data$dailymin, .data$dailymax)) %>%
      dplyr::mutate(AWMaxDiff = .data$dailymax_air - .data$dailymax_water,
             AirRange = .data$dailymax_air - .data$dailymin_air,
             WaterRange = .data$dailymax_water - .data$dailymin_water) %>%
      #pivot longer for plotting purposes later; to plot on same graph, need "calc" column ("grouping variable")
      tidyr::pivot_longer(cols = .data$dailymin_air:.data$WaterRange, names_to = "calc", values_to = "value")
  }else{
    Combined <- Combined %>%
      dplyr::rename(row = .data$V1, datetime = .data$V2, temp = .data$V3) %>%  # Rename the first three variables that came from the csv file
      dplyr::mutate(datetime = lubridate::ymd_hms(.data$datetime)) %>%  # change format of datetime column
      dplyr::mutate(date = lubridate::date(.data$datetime)) %>% # extract just the date
      dplyr::group_by(.data$sitename, .data$date, .data$media)  %>%  # compute daily max/min by site, date, and media (air/water)
      dplyr::summarize(dailymax = max(.data$temp, na.rm = TRUE),
                dailymin = min(.data$temp, na.rm = TRUE)) %>%
      # pivot dataframe to add air or water to column name; this is necessary to calculate stats
      # this puts air and water on the same rows so we can just subtract columns in the next line
      # this requires that at least one site has air temperature!
      tidyr::pivot_wider(names_from = .data$media,
                         values_from = c(.data$dailymin, .data$dailymax)) %>%
      dplyr::mutate(WaterRange = .data$dailymax_water - .data$dailymin_water) %>%
      #pivot longer for plotting purposes later; to plot on same graph, need "calc" column ("grouping variable")
      tidyr::pivot_longer(cols = .data$dailymin_water:.data$WaterRange, names_to = "calc", values_to = "value")
  }



  # set some plotting parameters
  sites <- unique(Combined$sitename)
  range.colors <- c(AirRange = "blue", WaterRange = "black")
  maxdiff.colors <- c(dailymax_air = "blue", dailymax_water = "black", AWMaxDiff = "purple")

  # loop through sites to plot all graphs for all sites
  i = 0
  for(s in sites){
    i = i+1
    cat(paste0("Making QC plots for site ", i, " of ", length(sites), ": ", s), fill = TRUE)
    # s = sites[1] # uncomment if you want to troubleshoot this loop
    # filter the data to just this site
    this.site.combined = dplyr::filter(Combined, .data$sitename == s)
    rangeplot <- ggplot2::ggplot(this.site.combined %>%
                                   dplyr::filter(.data$calc %in% c("AirRange","WaterRange")),
                                 ggplot2::aes(x = .data$date, y = .data$value, color = .data$calc)) +
      ggplot2::geom_line(na.rm=TRUE) +
      ggplot2::geom_point(na.rm=TRUE) +
      ggplot2::labs(title = paste0(s," Air and Water Temperature ranges"),
           x = "Date", y = "Temperature (C)",
           color = "Media") +
      ggplot2::scale_color_manual(values = range.colors) +
      ggplot2::geom_hline(yintercept = 3, linewidth = 0.3, color = "red")

    ggplot2::ggsave(paste0(qc_plots_loc, s, "_AirWaterTempRange.png"), rangeplot,
           width = 11, height = 8.5, units = "in")

    maxdiffplot <- ggplot2::ggplot(this.site.combined %>%
                                     dplyr::filter(.data$calc %in% c("dailymax_air", "dailymax_water", "AWMaxDiff")),
                            ggplot2::aes(x = .data$date, y = .data$value, color = .data$calc)) +
      ggplot2::geom_line(na.rm=TRUE) +
      ggplot2::labs(title = paste0(s," Max Air and Water Temperature and Difference"),
           x = "Date", y = "Temperature (C)",
           color = "Media") +
      ggplot2::scale_color_manual(values = maxdiff.colors) +
      ggplot2::geom_hline(yintercept = 20, linewidth = 0.3, color = "red")

    ggplot2::ggsave(paste0(qc_plots_loc, s, "_MaxDiffAirWaterTemp.png"),
           maxdiffplot, width = 11, height = 8.5, units = "in")

    maxdifplotly <- plotly::ggplotly(maxdiffplot)#to create plotly of maxdifplot to trace plot
    rangeplotly <- plotly::ggplotly(rangeplot)#to create plotly of rangeplot to trace plot

    htmlwidgets::saveWidget(maxdifplotly, paste0(qc_plots_loc, s, "_MaxDiffAirWaterTemp.html"))
    htmlwidgets::saveWidget(rangeplotly, paste0(qc_plots_loc, s, "_AirWaterTempRange.html"))
  }
  cat("Done.", fill = TRUE)
}
