#' Make QC plots of cropped data
#'
#' This function is intended to be used on cropped data, such as the csv files created by crop_raw_data().
#'
#' @param cropped_loc File path to the directory containing the cropped data
#' generated by crop_raw_data() to use in making QC plots. These files must be
#' in csv format. The names of the cropped data files must start with
#' <sitename>_<medium>_<deployseason>_<deployyear>. For example, a file with
#' air data from site NolanLower and deployment date Summer 2023 should have
#' a filename starting with NolanLower_air_sum_23, like
#' NolanLower_air_sum_23_cropped.csv.
#'
#' @param qc_plots_loc File path to the directory where QC plots will be stored.
#'
#' @return
#' @export
#'
#' @examples
#'
#' cropped_loc <- "data/2022_summer/2_cropped_csv/"
#' qc_plots_loc <- "data/2022_summer/3_qc_plots/"
#'
#' # get a list of all the cropped data files
#' filenames <- list.files(path = cropped_loc, pattern=".csv")
#' # this is now a list of all filenames; we haven't read in the data yet, but
#' # make sure this lists all the cropped data files you want to plot:
#' filenames
#'
#' # then make QC plots
#' make_qc_plots_of_cropped_data(cropped_loc, qc_plots_loc)
#'
make_qc_plots_of_cropped_data = function(cropped_loc, qc_plots_loc){

  # Make list of file names to plot
  filenames <- list.files(path = cropped_loc, pattern=".csv")

  # Loop to read all the data files and combine them into one datafile for easier plotting
  Combined <-NULL # Create new data frame to hold combined data

  print("Reading in cropped data files...")
  i = 0
  for (selection in filenames) {
    i = i+1
    #selection = filenames[1] # for troubleshooting the for-loop
    cat(paste0("Reading file ", i, " of ", length(filenames), ": ", selection), fill = TRUE)
    # split the filename string everywhere there is an underscore or period
    # so that we can get the following metadata from it:
    #  site name, deployment season and year, and media (air/water)
    info_from_filename = unlist(strsplit(selection, split="[_.]"))[1:4]
    sitename = info_from_filename[1]
    media = info_from_filename[2] # air or water; assumes this info is the third chunk after splitting the filename
    deploy_season = info_from_filename[3]
    if(deploy_season != "sum" & deploy_season != "fall"){
      stop("filename does not say sum or fall.")
    }
    deploy_year = 2000 + as.integer(info_from_filename[4]) # or we can format as character

    oneread <- read.csv(
      file=paste0(cropped_loc, selection), as.is=T, skip=1, fill=T, header=F
    ) %>% ## Reads the selected datafile.
      select(1:3) %>% #select the first 3 columns (remove air temp from Hoh River sites)
      # add the metadata as variables/columns
      mutate(sitename=sitename,
             media=media,
             deploy_season=deploy_season,
             deploy_year=deploy_year)
    Combined <- bind_rows(Combined, oneread)  ## Adds the datafile's data to the existing combined datafile.

  } # filenames loop
  cat("Done reading in cropped data.", fill = TRUE)

  cat("Computing temperature differences...", fill = TRUE)
  # only compute AWMaxDiff and AirRange if there is air data for at least one site
  if("air" %in% unique(Combined$media)){
    Combined <- Combined %>%
      rename(row=V1, datetime=V2, temp=V3) %>%  # Rename the first three variables that came from the csv file
      mutate(datetime = ymd_hms(datetime)) %>%  # change format of datetime column
      mutate(date = date(datetime)) %>%
      group_by(sitename, date, media)  %>%  # compute daily max/min by site, date, and media (air/water)
      summarize(dailymax = max(temp, na.rm = TRUE),
                dailymin = min(temp, na.rm = TRUE)) %>%
      # pivot dataframe to add air or water to column name; this is necessary to calculate stats
      # this puts air and water on the same rows so we can just subtract columns in the next line
      # this requires that at least one site has air temperature!
      pivot_wider(names_from = media, values_from = c(dailymin, dailymax)) %>%
      mutate(AWMaxDiff = dailymax_air - dailymax_water,
             AirRange = dailymax_air - dailymin_air,
             WaterRange = dailymax_water - dailymin_water) %>%
      #pivot longer for plotting purposes later; to plot on same graph, need "calc" column ("grouping variable")
      pivot_longer(cols = dailymin_air:WaterRange, names_to = "calc", values_to = "value")
  }else{
    Combined <- Combined %>%
      rename(row=V1, datetime=V2, temp=V3) %>%  # Rename the first three variables that came from the csv file
      mutate(datetime = ymd_hms(datetime)) %>%  # change format of datetime column
      mutate(date = date(datetime)) %>% # extract just the date
      group_by(sitename, date, media)  %>%  # compute daily max/min by site, date, and media (air/water)
      summarize(dailymax = max(temp, na.rm = TRUE),
                dailymin = min(temp, na.rm = TRUE)) %>%
      # pivot dataframe to add air or water to column name; this is necessary to calculate stats
      # this puts air and water on the same rows so we can just subtract columns in the next line
      # this requires that at least one site has air temperature!
      pivot_wider(names_from = media, values_from = c(dailymin, dailymax)) %>%
      mutate(WaterRange = dailymax_water - dailymin_water) %>%
      #pivot longer for plotting purposes later; to plot on same graph, need "calc" column ("grouping variable")
      pivot_longer(cols = dailymin_water:WaterRange, names_to = "calc", values_to = "value")
  }



  # set some plotting parameters
  sites <- unique(Combined$sitename)
  range.colors <- c(AirRange = "blue", WaterRange = "black")
  maxdiff.colors <- c(dailymax_air = "blue", dailymax_water = "black", AWMaxDiff = "purple")

  # loop through sites to plot all graphs for all sites
  i = 0
  for(s in sites){
    i = i+1
    cat(paste0("Making QC plots for site ", i, " of ", length(sites), ": ", s), fill = TRUE)
    # s = sites[1] # uncomment if you want to troubleshoot this loop
    # filter the data to just this site
    this.site.combined = filter(Combined, sitename == s)
    rangeplot <- ggplot(this.site.combined %>% filter(calc %in% c("AirRange","WaterRange")),
                        aes(x = date, y = value, color = calc)) +
      geom_line() +
      geom_point() +
      labs(title = paste0(s," Air and Water Temperature ranges"),
           x = "Date", y = "Temperature (C)",
           color = "Media") +
      scale_color_manual(values = range.colors) +
      geom_hline(yintercept = 3, linewidth = 0.3, color = "red")

    ggsave(paste0(qc_plots_loc, s, "_AirWaterTempRange.png"), rangeplot,
           width = 11, height = 8.5, units = "in")

    maxdiffplot <- ggplot(this.site.combined %>%
                            filter(calc %in% c("dailymax_air", "dailymax_water", "AWMaxDiff")),
                          aes(x = date, y = value, color = calc)) +
      geom_line() +
      labs(title = paste0(s," Max Air and Water Temperature and Difference"),
           x = "Date", y = "Temperature (C)",
           color = "Media") +
      scale_color_manual(values = maxdiff.colors) +
      geom_hline(yintercept = 20, linewidth = 0.3, color = "red")

    ggsave(paste0(qc_plots_loc, s, "_MaxDiffAirWaterTemp.png"),
           maxdiffplot, width = 11, height = 8.5, units = "in")

    maxdifplotly<-ggplotly(maxdiffplot)#to create plotly of maxdifplot to trace plot
    rangeplotly<-ggplotly(rangeplot)#to create plotly of rangeplot to trace plot

    htmlwidgets::saveWidget(maxdifplotly, paste0(qc_plots_loc, s, "_MaxDiffAirWaterTemp.html"))
    htmlwidgets::saveWidget(rangeplotly, paste0(qc_plots_loc, s, "_AirWaterTempRange.html"))
  }
  cat("Done.", fill = TRUE)
}
